version: '3'
services:
  flask:
    build: .
    container_name: flask-app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"
    command: python backend/main.py
